cache:
  timeout: 660
  pip: true
  custom_install: true
  directories:
    - remill-build/libraries
sudo: required
dist: trusty
language: generic
os: 
  - linux
compiler:
  - gcc
before_install:
  - git clone https://github.com/trailofbits/remill.git
  - mv mcsema remill/tools
install:
  - ./scripts/build_ubuntu.sh
before_script:
  - cd ../remill-build
  - make build_x86_tests
script:
  - make test
notifications:
  slack:
    secure: g1Nm7C7TYKg4RjDJ5cwuEcgKXfOAmVOu51adTPLBLGzZcCbCrkwQgI39ZycsalaACSnC8iNvqSCbRfZIA5mkDZ7VADaiZgLoWjq3RQzJmWgwGhhtyRkbtiicBnowTL5hIEiMOv6RnKlbB7M2OwzRiS07+FQXrK24hz+qm6zPptw=
